### ISSUE TITLE
Welcome: Invalid invite link to discord.

### ISSUE THREAD

**Issue by nikolasrieble** [dillonreedy/recharts-storybook#3]
**Describe the bug**
The invite link to discord is invalid.

**To Reproduce**
1. Go to the welcome page.
3. Click on `Discord chat`

**Expected behavior**
Entering a discord chat. 

**Screenshots**
<img width="633" alt="Screenshot 2022-10-02 at 20 48 11" src="https://user-images.githubusercontent.com/27995606/193470901-f83f5304-eeac-4738-b2e4-7939015126de.png">

**Comment by ckifer** [comment]
+1 - would like to join!

**Comment by dillonreedy** [comment]
@nikolasrieble @ckifer https://discord.gg/jSdp6TRu

And I'll fix where it is on the Storybook here in a minute.

When I originally launched this storybook. I made a discord, no one joined, so I took it down. It's good to finally see people wanting to use it!

@nikolasrieble let's move all communications onto there!

**Comment by dillonreedy** [comment]
@nikolasrieble and @ckifer discord is back up
