### ISSUE TITLE
Consider TypeScript-first Examples

### ISSUE THREAD

**Issue by ckifer** [dillonreedy/recharts-storybook#4]
Would like to propose writing these examples early on in TypeScript or supporting both JS and TS.

This gives benefits of:
* Type safety while writing examples ourselves
* TS examples for others to follow
* Increase maintainability, refactorability, etc

React without TS is no longer the standard in my experience

**Comment by nikolasrieble** [comment]
Totally agree, could you please create PR for a single new example fully in TS or alternatively porting a single example to TS?

**Comment by dillonreedy** [comment]
@ckifer @nikolasrieble just merged in the changes. Great first moves.

All the best
-D

**Comment by dillonreedy** [comment]
@ckifer and @nikolasrieble

For now, I think continuing in this same fashion where we create an issue on the repo for further changes we want done to specific components, we can gradually get to having Typescript examples piece-by-piece in this project.

So I'd advise just to make an issue if you'd like a Typescript example on a project, or a new component made up. We can tackle them as we progress along.

All the best
-D
